### PR TITLE
Shape classes

### PR DESCRIPTION
**Pull request by ChrisJAllan**
Drawing is a separate task.

TODO:
- [x] Keep `pos` in center for point-based shapes, make getters and setters use global positions
- [x] Unit tests
- [ ] QBrush/QPen property getters/setters?

### CODE REVIEW

**Review by tharvey5 — APPROVED** [review]

**Comment by tharvey5** [comment]
Chris - looks good, how do we get your work updated so I can clone this to my local repository

**Comment by ChrisJAllan** [comment]
There are still some changes I want to make to this, but for now you can checkout the `origin/chris-ShapeClasses` branch before making your own branch. Some of the getters/setters will change, but the constructors should stay the same.

**Comment by tharvey5** [comment]
Sounds good, thanks man much appreciated

**Comment by ChrisJAllan** [comment]
Alright, with that all changes to the interface are in, so I can merge this and then continue to work on the back-end a bit more.

**Comment by tharvey5** [comment]
Go ahead!

**Pull request merged**
